#!/bin/bash

# this script is to make symlinking all my dotfiles faster on new installs

# link vim
# -----------------
if [ ! -d "$HOME"/.vim ]; then #if no folder in home
  mkdir "$HOME"/.vim # make folder in home
fi
ln -sf "$PWD"/vim/* "$HOME"/.vim/

# link bashrc
# -----------
ln -sf "$PWD"/bashfiles/bashrc "$HOME"/.bashrc
