#!/bin/bash

# sym link dotfiles

# link .vim
# -----------------
if [ ! -d "$HOME"/.vim ]; then #if no folder in home
  mkdir "$HOME"/.vim # make folder in home
fi
ln -sf "$PWD"/vim/* "$HOME"/.vim/

# link bashrc
# -----------
ln -sf "$PWD"/bashfiles/bashrc "$HOME"/.bashrc
