" ##############################################################################
" Designed for vim 8+.  
" ##############################################################################

" References :- 
" rwxrob https://youtu.be/3mRBUUTL2Uo
" Max Cantor https://www.youtube.com/watch?v=XA2WjJbmmoM

" ##############################################################################
" colorscheme
" ##############################################################################

colorscheme elflord

" Sets the color of the colorcolumn
" :hi ColorColumn ctermbg=lightGreen guibg=lightgrey

" turns on 24 bit colors
set termguicolors   

" set background to dark mode
set background=dark

" rwxrob custom ruler
" set ruf=%30(%=%#LineNr#%.50F\ [%{strlen(&ft)?&ft:'none'}]\ %l:%c\ %p%%%)

" ##############################################################################
" settings
" ##############################################################################

" command history
set history=100

" This prevents truncated yanks, deletes, etc. (super important if using the vim
" buffers to paste stuff to a different file)
set viminfo='20,<1000,s1000

" makes it to avoid most of the 'Hit Enter ...' type messages
set shortmess=aoOtTI

" stops vim from silently messing with files that it shouldn't
set nofixendofline

" search wraps from bottom of file back to the top
set wrapscan

" ascii friendly charactors for when you want to see invisible charactors
set listchars=space:*,trail:*,nbsp:*,extends:>,precedes:<,tab:\|>
" set list

" turns off automatic folding
set foldmethod=manual

" if some folds where folded this will open them
 set nofoldenable

" Sets vi compatible mode to off (just use nvi for vi mode)
set nocompatible

" automatically indent new lines
set autoindent

" indenting for wrapped lines
set breakindent

" automatically write files when changing when multiple files are open
set autowrite

" shows the commands your using in the bottom tray
set showcmd

" Sets line numbers
set number

" disables relative line numbers
set norelativenumber

" turn col and row position on in the bottom right of tray
set ruler "

" Shows current mode in tray
set showmode

" no explaination yet
set tabstop=2

" disable visual bell
set t_vb=

" softtabstop, 
set softtabstop=2

" sets shiftwidth width (when you are in normal mode press >> or << and it will
" indent or go back this many spaces)
set shiftwidth=2

" Sets smart indenting
set smartindent

" sets smarttab, when smarttab is on it inserts blanks(which will be equal to whatever expand tab is
" set to) according to shiftwidth.
set smarttab

" mark trailing spaces as errors
" match IncSearch '\s\+$'

" Sets how wide inserted text can be (ie when horizontal lines will be wrapped)
set textwidth=80

" Sets a colored column in the vim terminal(for example you can set it to see where
" your textwidth ends) the +4 setting uses the textwidth then
" +4 to indicate where the column should go(it's +4 here and not +1 because line
" numbers are turned on, and they take up 3 columns)
" set colorcolumn=+4

" Sets tabs to equivelent amount of spaces
set expandtab

" set time out length in milliseconds(ie. for leaderkey timeout)
set timeout timeoutlen=2000

" makes an underline on what line the cursor is on
" set cursorline

" turn on default spell checking
" set spell

" disable spellcapcheck(it checks for a capital as the next word to find the
" end of a sentence) see :h spellcapcheck
set spellcapcheck=

" risky, but keeps your files and folders cleaner
set nobackup
set noswapfile
set nowritebackup

" no sure what this does, neither does rwxrob. He thought it had something to
" do with tmux window titles or something. Leaving it in
" I believe this just sets the icon text for the window, only works on x11
" gui's. the icon text uses the file name unless you set iconstring to something
" non empty
set icon

" sets how much room the cursor has to move  up and down the screen
set scrolloff=8

" set highlight search hits
set hlsearch

" displays the match when your only partially through typing it
set incsearch

" linebreak, if on wraps can occur at whatever breakat is
" set linebreak

" turns bracket matching off
" let g:loaded_matchparen=1

" cursor quickly jumps to a matching bracket
" set showmatch

" faster scrolling
set ttyfast

" Sets up a way to do fuzzy finding
" **(as in star star) tells vim that when you look for a file search through every
" subdirectory, and search through every subdirectory of every subdirectory, see
" max cantor's presentation
set path+=**

" Display all matching files when we tab complete, apparently this can be
" configured several different ways
set wildmenu

" Set syntax on
syntax enable

" :h ins-completion for the auto complete man page

" ##############################################################################
" Plugins
" ##############################################################################

" enable loading the plugin files for specific file types
filetype plugin on

" Rob recommeds to use the Plug plugin manager, as it doesn't mess around with
" your stuff, and it helps to keep everything clean and separated. see his video
" for more

" autoload plug if not present
if empty(glob('~/.vim/autoload/plug.vim'))
  silent !curl -fLo ~/.vim/autoload/plug.vim --create-dirs
    \ https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
endif

" start of plugins section
call plug#begin('~/.vim/plugged')

Plug 'https://github.com/tpope/vim-surround'

Plug 'https://github.com/tpope/vim-repeat'

Plug 'https://github.com/gbjnewman/live-server-vim'

Plug 'https://github.com/preservim/nerdtree'

call plug#end()

" see :h write-filetype-plugin to see how to
" write my own filetype plugins, also see :h write-plugin

" ##############################################################################
" key maps
" ##############################################################################

" set mapleader
let mapleader=","

" nerdtree open/close toggle
nnoremap <LEADER>n :NERDTreeToggle<CR>

" remap split window navigation
nnoremap <C-h> <C-w>h
nnoremap <C-l> <C-w>l
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k

" map Y to act the same way as D and C (in that it does the action to the end of line)
nnoremap Y y$

" map H to move to the beginning of the line
nnoremap H ^

" map L to move to the end of the line
nnoremap L $

" mapping for function keys, the ! at the end before <CR> is to make it so you
" can toggle on and off
map <F1> :set number!<CR>
map <F2> :set relativenumber!<CR>
set pastetoggle=<F3>   " not sure why its done this way, i just copied rwxrob
map <F4> :set list!<CR>
map <F5> :set cursorline!<CR>
map <F6> :set nohlsearch!<CR>
map <F7> :set spell!<CR>
" map <F12> :set fdm=indent<CR>

" add line without going into insert mode
nnoremap <leader>o o<esc>k

" edit vimrc from current session
nnoremap <leader>evim :e $HOME/.vim/vimrc<CR>

" source vimrc from current session
nnoremap <leader>svim :source $HOME/.vim/vimrc<CR>

" reads in html template
nnoremap <leader>html :-1read $HOME/.vim/snippets/html<CR>8j3wa

" ##############################################################################
" autocommands
" ##############################################################################

" Start NERDTree and leave the cursor in it.
autocmd VimEnter * NERDTree

" Exit Vim if NERDTree is the only window remaining in the only tab.
autocmd BufEnter * if tabpagenr('$') == 1 && winnr('$') == 1 && exists('b:NERDTree') && b:NERDTree.isTabTree() | quit | endif

" ##############################################################################
" End
" ##############################################################################
